const ALERT_COMMAND_MESSAGE = {
  NOTIFICATION_REQUEST: "CMD_MWDEV:NOTIFICATION_REQUEST",
  RECONNECT_GRPC: "CMD_MWDEV:RECONNECT_GRPC",
  MEETING_ALERT: "CMD_MWDEV:MEETING_ALERT",
};

export default ALERT_COMMAND_MESSAGE;
