export const NAME_VALIDATION_ERROR_CODE = {
  NAME_LENGTH_TOO_LONG: "NAME_LENGTH_TOO_LONG",
  CONTAIN_NOT_ALLOW_CHAR: "CONTAIN_NOT_ALLOW_CHAR",
};

export const DESCRIPTION_VALIDATION_ERROR_CODE = {
  DESCRIPTION_LENGTH_TOO_LONG: "NAME_LENGTH_TOO_LONG",
};
